import logging
from enum import Enum

from src.specialist import Specialist


class SubSpecialtyDxGroup(Enum):
    Generalist = ('general', Specialist.Generalist)
    FertilityConditions = ('FertilityConditions', Specialist.Generalist)
    NutritionalDeficiency = ('NutritionalDeficiency', Specialist.Generalist)
    CancerOther = ('Cancer_Other', Specialist.Generalist)
    PainSyndrome = ('Painsyndrome', Specialist.Generalist)
    ChronicPain = ('Chronic_Pain', Specialist.Generalist)
    Fatigue = ('Fatigue', Specialist.Generalist)
    Lymphadenopathy = ('Lymphadenopathy', Specialist.Generalist)
    AnimalBite = ('Animal_bite', Specialist.Generalist)
    GeneralistOther = ('GeneralistOther', Specialist.Generalist)
    PostOperativeComplications = ('PostOperativeComplications', Specialist.Generalist)
    Tumor = ('Tumor', Specialist.Generalist)
    AppetiteLoss = ('AppetiteLoss', Specialist.Generalist)
    WeightGain = ('WeightGain', Specialist.Generalist)

    CoronaryArteryDisease = ('CoronaryArteryDisease', Specialist.CardiovascularSpecialist)
    Hypertension = ('Hypertension', Specialist.CardiovascularSpecialist)
    Hypotension = ('Hypotension', Specialist.CardiovascularSpecialist)
    CongestiveHeartFailure = ('CongestiveHeartFailure', Specialist.CardiovascularSpecialist)
    AtrialFibrillation = ('AtrialFibrillation', Specialist.CardiovascularSpecialist)
    MyocardialInfarction = ('HeartAttack', Specialist.CardiovascularSpecialist)
    AcuteCoronarySyndrome = ('AcuteCoronarySyndrome', Specialist.CardiovascularSpecialist)
    ValvularHeartDisease = ('ValvularHeartDisease', Specialist.CardiovascularSpecialist)
    Arrhythmias = ('Arrhythmias', Specialist.CardiovascularSpecialist)
    Cardiomyopathy = ('Cardiomyopathy', Specialist.CardiovascularSpecialist)
    PeripheralArteryDisease = ('PeripheralArteryDisease', Specialist.CardiovascularSpecialist)
    HeartValveDisorders = ('HeartValveDisorders', Specialist.CardiovascularSpecialist)
    PulmonaryHypertension = ('PulmonaryHypertension', Specialist.CardiovascularSpecialist)
    DeepVeinThrombosis = ('DVT', Specialist.CardiovascularSpecialist)
    AorticAneurysm = ('AorticAneurysm', Specialist.CardiovascularSpecialist)
    MitralValveProlapse = ('MitralValveProlapse', Specialist.CardiovascularSpecialist)
    PericardialDiseases = ('PericardialDiseases', Specialist.CardiovascularSpecialist)
    HighCholesterol = ('Hyperlipidemia', Specialist.CardiovascularSpecialist)
    Syncope = ('Syncope', Specialist.CardiovascularSpecialist)
    CongenitalHeartDefects = ('CongenitalHeartDefects', Specialist.CardiovascularSpecialist)
    HeartMurmurs = ('HeartMurmurs', Specialist.CardiovascularSpecialist)
    HighBloodPressure = ('HighBloodPressure', Specialist.CardiovascularSpecialist)
    VenousInsufficiency = ('VenousInsufficiency', Specialist.CardiovascularSpecialist)
    CardiovascularOther = ('CardiovascularOther', Specialist.CardiovascularSpecialist)
    Edema = ('Edema', Specialist.CardiovascularSpecialist)

    Asthma = ('Asthma', Specialist.Pulmonologist)
    Cough = ('Cough', Specialist.Pulmonologist)
    COPD = ('ChronicObstructivePulmonaryDisease', Specialist.Pulmonologist)
    Pneumonia = ('Pneumonia', Specialist.Pulmonologist)
    Bronchitis = ('Bronchitis', Specialist.Pulmonologist)
    Emphysema = ('Emphysema', Specialist.Pulmonologist)
    Pleurisy = ('Pleurisy', Specialist.Pulmonologist)
    PulmonaryEmbolism = ('PulmonaryEmbolism', Specialist.Pulmonologist)
    Tuberculosis = ('Tuberculosis', Specialist.Pulmonologist)
    CysticFibrosis = ('CysticFibrosis', Specialist.Pulmonologist)
    SleepApnea = ('SleepApnea', Specialist.Pulmonologist)
    ARDS = ('ARDS', Specialist.Pulmonologist)
    LungCancer = ('LungCancer', Specialist.Pulmonologist)
    PleuralConditions = ('PleuralConditions', Specialist.Pulmonologist)
    EnvironmentalRelatedRespiratoryCondition = ('EnvironmentalRelatedRespiratoryCondtion', Specialist.Pulmonologist)
    PulmonologyOther = ('PulmonologyOther', Specialist.Pulmonologist)

    DiabetesMellitus = ('DiabetesMellitus', Specialist.Endocrinologist)
    ThyroidDisorders = ('ThyroidDisorders', Specialist.Endocrinologist)
    Obesity = ('Obesity', Specialist.Endocrinologist)
    Osteoporosis = ('Osteoporosis', Specialist.Endocrinologist)
    AdrenalGlandDisorders = ('AdrenalGlandDisorders', Specialist.Endocrinologist)
    PituitaryGlandDisorders = ('PituitaryGlandDisorders', Specialist.Endocrinologist)
    ParathyroidDisorders = ('ParathyroidDisorders', Specialist.Endocrinologist)
    MetabolicSyndrome = ('MetabolicSyndrome', Specialist.Endocrinologist)
    Hyperlipidemia = ('HighCholesterol', Specialist.Endocrinologist)
    Hypoglycemia = ('Hypoglycemia', Specialist.Endocrinologist)
    Hypopituitarism = ('Hypopituitarism', Specialist.Endocrinologist)
    GrowthHormoneDisorders = ('GrowthHormoneDisorders', Specialist.Endocrinologist)
    ThyroidNodules = ('ThyroidNodules', Specialist.Endocrinologist)
    ThyroidCancer = ('ThyroidCancer', Specialist.Endocrinologist)
    CushingsSyndrome = ('CushingsSyndrome', Specialist.Endocrinologist)
    AddisonsDisease = ('AddisonsDisease', Specialist.Endocrinologist)
    MENSyndromes = ('MENSyndromes', Specialist.Endocrinologist)
    Pheochromocytoma = ('Pheochromocytoma', Specialist.Endocrinologist)
    Gynecomastia = ('Gynecomastia', Specialist.Endocrinologist)
    WeightLoss = ('Weightloss', Specialist.Endocrinologist)
    EndocrinologyOther = ('EndocrinologyOther', Specialist.Endocrinologist)
    TestosteroneConditions = ('TestosteroneConditions', Specialist.Endocrinologist)
    DependentEdema = ('DependentEdema', Specialist.Endocrinologist)

    GERD = ('GERD', Specialist.Gastroenterologist)
    IBS = ('IBS', Specialist.Gastroenterologist)
    IBD = ('InflammatoryBowelDisease', Specialist.Gastroenterologist)
    PepticUlcers = ('PepticUlcers', Specialist.Gastroenterologist)
    Gallstones = ('Gallstones', Specialist.Gastroenterologist)
    CeliacDisease = ('CeliacDisease', Specialist.Gastroenterologist)
    GastrointestinalBleeding = ('GastrointestinalBleeding', Specialist.Gastroenterologist)
    Pancreatitis = ('Pancreatitis', Specialist.Gastroenterologist)
    Hepatitis = ('Hepatitis', Specialist.Gastroenterologist)
    Diverticulitis = ('Diverticulitis', Specialist.Gastroenterologist)
    Gastroenteritis = ('Gastroenteritis', Specialist.Gastroenterologist)
    ColorectalCancer = ('ColorectalCancer', Specialist.Gastroenterologist)
    BarrettsEsophagus = ('BarrettsEsophagus', Specialist.Gastroenterologist)
    Hemorrhoids = ('Hemorrhoids', Specialist.Gastroenterologist)
    GastrointestinalPolyps = ('GastrointestinalPolyps', Specialist.Gastroenterologist)
    GastrointestinalMotilityDisorders = ('GastrointestinalMotilityDisorders', Specialist.Gastroenterologist)
    MalabsorptionSyndromes = ('MalabsorptionSyndromes', Specialist.Gastroenterologist)
    EosinophilicEsophagitis = ('EosinophilicEsophagitis', Specialist.Gastroenterologist)
    GastrointestinalStrictures = ('GastrointestinalStrictures', Specialist.Gastroenterologist)
    PancreasDisorders = ('PancreasDisorders', Specialist.Gastroenterologist)
    HerniaDisorders = ('HerniaDisorders', Specialist.Gastroenterologist)
    NAFLD = ('NonAlcoholicFattyLiverDisease', Specialist.Gastroenterologist)
    Gastritis = ('Gastritis', Specialist.Gastroenterologist)
    Cirrhosis = ('Cirrhosis', Specialist.Gastroenterologist)
    LiverConditons = ('LiverConditons', Specialist.Gastroenterologist)
    AnalandRectalConditions = ('AnalandRectalConditions', Specialist.Gastroenterologist)
    GastroenterologyOther = ('GastroenterologyOther', Specialist.Gastroenterologist)
    Diarrhea = ('Diarrhea', Specialist.Gastroenterologist)
    BilliaryIssues = ('BilliaryIssues', Specialist.Gastroenterologist)
    Constipation = ('Constipation', Specialist.Gastroenterologist)
    CancerGIOther = ('Cancer_GIother', Specialist.Gastroenterologist)
    BiliaryIssues = ('BiliaryIssues', Specialist.Gastroenterologist)
    Vomiting = ('Vomiting', Specialist.Gastroenterologist)
    DietaryIntolerance = ('DietaryIntolerance', Specialist.Gastroenterologist)
    GastrointestinalDistressSx = ('GastrointestinalDistressSx', Specialist.Gastroenterologist)
    ConstipationConditions = ('ConstipationConditions', Specialist.Gastroenterologist)
    BluntAbdominalTrauma = ('BluntAbdominalTrauma', Specialist.Gastroenterologist)

    Influenza = ('Influenza', Specialist.InfectiousDiseaseSpecialist)
    HIV_AIDS = ('HIV_AIDS', Specialist.InfectiousDiseaseSpecialist)
    COVID_19 = ('COVID_19', Specialist.InfectiousDiseaseSpecialist)
    STIs = ('STIs', Specialist.InfectiousDiseaseSpecialist)
    LymeDisease = ('LymeDisease', Specialist.InfectiousDiseaseSpecialist)
    Malaria = ('Malaria', Specialist.InfectiousDiseaseSpecialist)
    Meningitis = ('Meningitis', Specialist.InfectiousDiseaseSpecialist)
    Sepsis = ('Sepsis', Specialist.InfectiousDiseaseSpecialist)
    UTIs = ('UTIs', Specialist.InfectiousDiseaseSpecialist)
    RespiratoryTractInfections = ('RespiratoryTractInfections', Specialist.InfectiousDiseaseSpecialist)
    BacterialInfections = ('BacterialInfections', Specialist.InfectiousDiseaseSpecialist)
    FungalInfections = ('FungalInfections', Specialist.InfectiousDiseaseSpecialist)
    ParasiticInfections = ('ParasiticInfections', Specialist.InfectiousDiseaseSpecialist)
    VectorBorneDiseases = ('VectorBorneDiseases', Specialist.InfectiousDiseaseSpecialist)
    ZoonoticDiseases = ('ZoonoticDiseases', Specialist.InfectiousDiseaseSpecialist)
    InfectiousDiseasesOther = ('InfectiousDiseasesOther', Specialist.InfectiousDiseaseSpecialist)
    RespiratoryTractInfectionsUpperViral = ('RespiratoryTractInfections-upper-viral', Specialist.InfectiousDiseaseSpecialist)
    GastrointestinalInfections = ('GastrointestinalInfections', Specialist.InfectiousDiseaseSpecialist)

    Migraine = ('Migraine', Specialist.Neurologist)
    Epilepsy = ('Epilepsy', Specialist.Neurologist)
    Stroke = ('Stroke', Specialist.Neurologist)
    AlzheimersDisease = ('AlzheimersDisease', Specialist.Neurologist)
    ParkinsonsDisease = ('ParkinsonsDisease', Specialist.Neurologist, 'parkinsons')
    MultipleSclerosis = ('MultipleSclerosis', Specialist.Neurologist)
    ALS = ('ALS', Specialist.Neurologist)
    TraumaticBrainInjury = ('TraumaticBrainInjury', Specialist.Neurologist)
    Neuropathy = ('Neuropathy', Specialist.Neurologist)
    HuntingtonsDisease = ('HuntingtonsDisease', Specialist.Neurologist)
    Dementia = ('Dementia', Specialist.Neurologist)
    CerebralPalsy = ('CerebralPalsy', Specialist.Neurologist)
    RestlessLegsSyndrome = ('RestlessLegsSyndrome', Specialist.Neurologist)
    TouretteSyndrome = ('TouretteSyndrome', Specialist.Neurologist)
    NeurodegenerativeDisorders = ('NeurodegenerativeDisorders', Specialist.Neurologist)
    BrainTumors = ('BrainTumors', Specialist.Neurologist)
    MyastheniaGravis = ('MyastheniaGravis', Specialist.Neurologist)
    BellsPalsy = ('BellsPalsy', Specialist.Neurologist)
    Narcolepsy = ('Narcolepsy', Specialist.Neurologist)
    CNSInfections = ('CNSInfections', Specialist.Neurologist)
    NeurologyConditionsOther = ('NeurologyConditionsOther', Specialist.Neurologist)
    HeadAcheOther = ('HeadAcheOther', Specialist.Neurologist)
    MovementDisorderOther = ('MovementDisorderOther', Specialist.Neurologist)
    Encephalopathy = ('Encephalopathy', Specialist.Neurologist)
    AgeRelatedChangesNormal = ('AgeRelatedChanges_Normal', Specialist.Neurologist)
    SeizureorSeizureDisorder = ('SeizureorSeizureDisorder', Specialist.Neurologist)
    EssentialTremor = ('EssentialTremor', Specialist.Neurologist)
    PostCOVIDComplications = ('Post-COVID_complications', Specialist.Neurologist)
    CognitiveImpairment = ('CognitiveImpairment', Specialist.Neurologist)

    Acne = ('Acne', Specialist.Dermatologist)
    Rash = ('Rash', Specialist.Dermatologist)
    Eczema = ('Eczema', Specialist.Dermatologist)
    Psoriasis = ('Psoriasis', Specialist.Dermatologist)
    SkinInfections = ('SkinInfections', Specialist.Dermatologist)
    Rosacea = ('Rosacea', Specialist.Dermatologist)
    DermatologicalAllergies = ('DermatologicalAllergies', Specialist.Dermatologist)
    Hives = ('Hives', Specialist.Dermatologist)
    Warts = ('Warts', Specialist.Dermatologist)
    SkinCancer = ('SkinCancer', Specialist.Dermatologist)
    Melanoma = ('Melanoma', Specialist.Dermatologist)
    BasalCellCarcinoma = ('BasalCellCarcinoma', Specialist.Dermatologist)
    SquamousCellCarcinoma = ('SquamousCellCarcinoma', Specialist.Dermatologist)
    Vitiligo = ('Vitiligo', Specialist.Dermatologist)
    Alopecia = ('Alopecia', Specialist.Dermatologist)
    AtopicDermatitis = ('AtopicDermatitis', Specialist.Dermatologist)
    ContactDermatitis = ('ContactDermatitis', Specialist.Dermatologist)
    Pruritus = ('Pruritus', Specialist.Dermatologist)
    SeborrheicDermatitis = ('SeborrheicDermatitis', Specialist.Dermatologist)
    LupusErythematosus = ('LupusErythematosus', Specialist.Dermatologist)
    Dermatitis = ('Dermatitis', Specialist.Dermatologist)
    InsectStingOrBiteOrReaction = ('Insect_StingorBiteorReaction', Specialist.Dermatologist)
    Nevus = ('Nevus', Specialist.Dermatologist)
    XerosisDryDkin = ('Xerosis_dryskin', Specialist.Dermatologist)
    IrritationPhysicalContact = ('Irritation_PhysicalContact', Specialist.Dermatologist)
    BruiseorContusion = ('BruiseorContusion', Specialist.Dermatologist)
    SkinLesionNos = ('SkinLesionNos', Specialist.Dermatologist)
    HairConditions = ('HairConditions', Specialist.Dermatologist)
    NailDisorders = ('Nail_Disorders', Specialist.Dermatologist)
    Burn = ('Burn', Specialist.Dermatologist)
    RadiationSideEffects = ('RadiationSideeffects', Specialist.Dermatologist)
    DermPigmentedLesionOther = ('DermPigmentedLesionOther', Specialist.Dermatologist)
    SkinUlcer = ('SkinUlcer', Specialist.Dermatologist)
    Infestations = ('Infestations', Specialist.Dermatologist)
    FacialBirthDefect = ('FacialBirthDefect', Specialist.Dermatologist)
    DermatologyConditionsOther = ('DermatologyConditionsOther', Specialist.Dermatologist)
    DermatologyCosemetics = ('Dermatology_cosemetics', Specialist.Dermatologist)
    CornsCalluses = ('Corns_Calluses', Specialist.Dermatologist)
    SkinPigmentation = ('SkinPigmentation', Specialist.Dermatologist)
    SkinAndSoftTissueInfections = ('SkinAndSoftTissueInfections', Specialist.Dermatologist)

    MajorDepressiveDisorder = ('MajorDepressiveDisorder', Specialist.Psychiatrist)
    GeneralizedAnxietyDisorder = ('GeneralizedAnxietyDisorder', Specialist.Psychiatrist)
    BipolarDisorder = ('BipolarDisorder', Specialist.Psychiatrist)
    Schizophrenia = ('Schizophrenia', Specialist.Psychiatrist)
    OCD = ('ObsessiveCompulsiveDisorder', Specialist.Psychiatrist)
    PTSD = ('PostTraumaticStressDisorder', Specialist.Psychiatrist)
    PanicDisorder = ('PanicDisorder', Specialist.Psychiatrist)
    SocialAnxietyDisorder = ('SocialAnxietyDisorder', Specialist.Psychiatrist)
    ADHD = ('ADHD', Specialist.Psychiatrist)
    EatingDisorders = ('EatingDisorders', Specialist.Psychiatrist)
    BorderlinePersonalityDisorder = ('BorderlinePersonalityDisorder', Specialist.Psychiatrist)
    AntisocialPersonalityDisorder = ('AntisocialPersonalityDisorder', Specialist.Psychiatrist)
    PersonalityDisordersOther = ('PersonalityDisordersOther', Specialist.Psychiatrist)
    AutismSpectrumDisorders = ('AutismSpectrumDisorders', Specialist.Psychiatrist)
    SchizoaffectiveDisorder = ('SchizoaffectiveDisorder', Specialist.Psychiatrist)
    DissociativeDisorders = ('DissociativeDisorders', Specialist.Psychiatrist)
    InsomniaAndOtherSleepDisorders = ('InsomniaAndOtherSleepDisorders', Specialist.Psychiatrist)
    DelusionalDisorders = ('DelusionalDisorders', Specialist.Psychiatrist)
    HoardingDisorder = ('HoardingDisorder', Specialist.Psychiatrist)
    GenderDysphoria = ('GenderDysphoria', Specialist.Psychiatrist)
    DissociativeConditions = ('DissociativeConditions', Specialist.Psychiatrist)
    AdjustmentDisorder = ('AdjustmentDisorder', Specialist.Psychiatrist)
    Stress = ('Stress', Specialist.Psychiatrist)
    AnxietyNOS = ('AnxietyNOS', Specialist.Psychiatrist)
    Anxiety = ('Anxiety', Specialist.Psychiatrist)
    Depression = ('Depression', Specialist.Psychiatrist)
    AnxietyDisorders = ('AnxietyDisorders', Specialist.Psychiatrist)
    PersonalityDisorder = ('PersonalityDisorder', Specialist.Psychiatrist)
    PsychosisOrDelusionalDisorder = ('Psychosis_or_DelusionalDisorder', Specialist.Psychiatrist)
    Phobia = ('Phobia', Specialist.Psychiatrist)
    MoodDisorderOther = ('MoodDisorderOther', Specialist.Psychiatrist)
    SexualFunctionConditions = ('SexualFunctionConditions', Specialist.Psychiatrist)
    PsychiatryOther = ('PsychiatryOther', Specialist.Psychiatrist)

    Osteoarthritis = ('Osteoarthritis', Specialist.Orthopedist)
    Fractures = ('Fractures', Specialist.Orthopedist)
    Tendonitis = ('Tendonitis', Specialist.Orthopedist)
    SprainsAndStrains = ('SprainsAndStrains', Specialist.Orthopedist)
    BackPain = ('BackPain', Specialist.Orthopedist)
    CarpalTunnelSyndrome = ('CarpalTunnelSyndrome', Specialist.Orthopedist)
    RotatorCuffInjuries = ('RotatorCuffInjuries', Specialist.Orthopedist)
    Scoliosis = ('Scoliosis', Specialist.Orthopedist)
    Bursitis = ('Bursitis', Specialist.Orthopedist)
    MeniscusTears = ('MeniscusTears', Specialist.Orthopedist)
    ACLInjuries = ('ACLInjuries', Specialist.Orthopedist)
    PCLInjuries = ('PCLInjuries', Specialist.Orthopedist)
    PatellofemoralPainSyndrome = ('PatellofemoralPainSyndrome', Specialist.Orthopedist)
    OsgoodSchlatterDisease = ('OsgoodSchlatterDisease', Specialist.Orthopedist)
    PatellarTendonitis = ('PatellarTendonitis', Specialist.Orthopedist)
    BakersCyst = ('BakersCyst', Specialist.Orthopedist)
    ITBS = ('IliotibialBandSyndrome', Specialist.Orthopedist)
    ShoulderConditions = ('ShoulderConditions', Specialist.Orthopedist)
    NeckPain = ('NeckPain', Specialist.Orthopedist)
    KneeConditions = ('Knee Conditions', Specialist.Orthopedist)
    Hipdisorders = ('Hipdisorders', Specialist.Orthopedist)
    Myopathy = ('Myopathy', Specialist.Orthopedist)
    Dislocation = ('Dislocation', Specialist.Orthopedist)
    CancerBone = ('Cancer_Bone', Specialist.Orthopedist)
    OrthopedicConditionsOther = ('OrthopedicConditionsOther', Specialist.Orthopedist)
    AvascularNecrosis = ('AvascularNecrosis', Specialist.Orthopedist)
    WristSprain = ('WristSprain', Specialist.Orthopedist)

    Tonsillitis = ('Tonsillitis', Specialist.Otolaryngologist)
    OtitisMedia = ('OtitisMedia', Specialist.Otolaryngologist)
    Sinusitis = ('Sinusitis', Specialist.Otolaryngologist)
    AllergicRhinitis = ('AllergicRhinitis', Specialist.Otolaryngologist)
    HearingLoss = ('HearingLoss', Specialist.Otolaryngologist)
    Laryngitis = ('Laryngitis', Specialist.Otolaryngologist)
    SwimmersEar = ('SwimmersEar', Specialist.Otolaryngologist)
    VertigoAndDizziness = ('VertigoAndDizziness', Specialist.Otolaryngologist)
    VoiceDisorders = ('VoiceDisorders', Specialist.Otolaryngologist)
    NasalPolyps = ('NasalPolyps', Specialist.Otolaryngologist)
    DeviatedSeptum = ('DeviatedSeptum', Specialist.Otolaryngologist)
    EarwaxBlockage = ('EarwaxBlockage', Specialist.Otolaryngologist)
    Hoarseness = ('Hoarseness', Specialist.Otolaryngologist)
    Tinnitus = ('Tinnitus', Specialist.Otolaryngologist)
    BPPV = ('BenignParoxysmalPositionalVertigo', Specialist.Otolaryngologist)
    NasalFractures = ('NasalFractures', Specialist.Otolaryngologist)
    TMJDisorders = ('TemporomandibularJointDisorders', Specialist.Otolaryngologist)
    HeadAndNeckCancer = ('HeadAndNeckCancer', Specialist.Otolaryngologist)
    SalivaryGlandDisorders = ('SalivaryGlandDisorders', Specialist.Otolaryngologist)
    Pharyngitis = ('Pharygitis', Specialist.Otolaryngologist)
    EarInfections = ('EarInfections', Specialist.Otolaryngologist)
    NasalConditions = ('NasalConditions', Specialist.Otolaryngologist)
    Rhinitis = ('Rhinitis', Specialist.Otolaryngologist)
    DryAirInducedSymptoms = ('DryAir-InducedSymptoms', Specialist.Otolaryngologist)
    ForeignBodyEmbedded = ('ForeignBody_embedded', Specialist.Otolaryngologist)
    PharygitisNOS = ('PharygitisNOS', Specialist.Otolaryngologist)
    CancerHeadandNeck = ('Cancer_HeadandNeck', Specialist.Otolaryngologist)
    OtolaryngologyOther = ('OtolaryngologyOther', Specialist.Otolaryngologist)
    Epistaxis = ('Epistaxis', Specialist.Otolaryngologist)
    OralLesions = ('OralLesions', Specialist.Otolaryngologist)

    RefractiveErrors = ('Refractive Error', Specialist.Ophthalmologist)
    Cataract = ('Cataract', Specialist.Ophthalmologist)
    Glaucoma = ('Glaucoma', Specialist.Ophthalmologist)
    AMD = ('AgeRelatedMacularDegeneration', Specialist.Ophthalmologist)
    DiabeticRetinopathy = ('DiabeticRetinopathy', Specialist.Ophthalmologist)
    RetinalDetachment = ('RetinalDetachment', Specialist.Ophthalmologist)
    PinkEye = ('Conjunctivitis', Specialist.Ophthalmologist)
    DryEyeSyndrome = ('DryEyeSyndrome', Specialist.Ophthalmologist)
    CornealDisorders = ('CornealDisorders', Specialist.Ophthalmologist)
    Strabismus = ('Strabismus', Specialist.Ophthalmologist)
    OphthalmologyOther = ('OphthalmologyOther', Specialist.Ophthalmologist)
    CorneaConditions = ('Cornea_Condition', Specialist.Ophthalmologist)
    EyeMisalignment = ('EyeMisalignment', Specialist.Ophthalmologist)
    EyeTrauma = ('EyeTrauma', Specialist.Ophthalmologist)
    EyelidCondition = ('EyelidCondition', Specialist.Ophthalmologist)
    RetinalCondition = ('RetinalCondition', Specialist.Ophthalmologist)
    EyePeriOrbitalCondition = ('EyePeriorbitalCondition', Specialist.Ophthalmologist)
    EyePupilCondition = ('EyePupilCondition', Specialist.Ophthalmologist)
    Uveitis = ('Uveitis', Specialist.Ophthalmologist)
    EyeConjunctivalConditionOther = ('EyeConjunctivalConditionOther', Specialist.Ophthalmologist)
    EyeTearDuctCondition = ('EyeTearDuctCondition', Specialist.Ophthalmologist)
    EyeVitreousCondition = ('EyeVitreousCondition', Specialist.Ophthalmologist)
    EyeScleraCondition = ('EyeScleraCondition', Specialist.Ophthalmologist)
    EyePosteriorCapsuleConditions = ('EyePosteriorCapsuleConditions', Specialist.Ophthalmologist)
    OcularTrauma = ('OcularTrauma', Specialist.Ophthalmologist)

    BPH = ('BenignProstaticHyperplasia', Specialist.Urologist)
    ProstateCancer = ('ProstateCancer', Specialist.Urologist)
    KidneyStones = ('KidneyStones', Specialist.Urologist)
    ErectileDysfunction = ('ErectileDysfunction', Specialist.Urologist)
    Incontinence = ('Incontinence', Specialist.Urologist)
    InterstitialCystitis = ('InterstitialCystitis', Specialist.Urologist)
    UrinaryRetention = ('UrinaryRetention', Specialist.Urologist)
    Prostatitis = ('Prostatitis', Specialist.Urologist)
    TesticularCancer = ('TesticularCancer', Specialist.Urologist)
    UrologyMenOther = ('UrologyMenOther', Specialist.Urologist)
    UrologyOther = ('UrologyOther', Specialist.Urologist)
    CongenitalMalformationOther = ('CongenitalMalformation_Other', Specialist.Urologist)
    UrethritisNonGC = ('Urethritis_nonGC', Specialist.Urologist)
    SemenConditions = ('SemenConditions', Specialist.Urologist)
    PenisConditions = ('PenisConditions', Specialist.Urologist)
    BladderCancer = ('BladderCancer', Specialist.Urologist)

    VaginalInfections = ('VaginalInfections', Specialist.Gynecologist)
    Vulvitis = ('Vulvitis', Specialist.Gynecologist)
    AbnormalUterineBleeding = ('AbnormalUterineBleeding', Specialist.Gynecologist)
    PelvicPain = ('PelvicPain', Specialist.Gynecologist)
    Menopause = ('Menopause', Specialist.Gynecologist)
    CervicalCancer = ('CervicalCancer', Specialist.Gynecologist)
    OvarianCysts = ('OvarianCysts', Specialist.Gynecologist)
    Endometriosis = ('Endometriosis', Specialist.Gynecologist)
    Adenomyosis = ('Adenomyosis', Specialist.Gynecologist)
    UterineFibroids = ('UterineFibroids', Specialist.Gynecologist)
    PCOS = ('PolycysticOvarySyndrome', Specialist.Gynecologist, 'pcos')
    BreastCancer = ('BreastCancer', Specialist.Gynecologist)
    BreastChanges = ('BreastChanges', Specialist.Gynecologist)
    SexuallyTransmittedInfections = ('SexuallyTransmittedInfections(STI)', Specialist.Gynecologist)
    PelvicInfection = ('PelvicInfection', Specialist.Gynecologist)
    GynecologyOther = ('GynecologyOther', Specialist.Gynecologist)
    BreastConditions = ('Breast Conditions', Specialist.Gynecologist)
    MenstrualConditions = ('Menstrual Conditions', Specialist.Gynecologist)
    Amennorrhea = ('Amennorrhea', Specialist.Gynecologist)
    VaginalCondtiionOther = ('VaginalCondtiionOther', Specialist.Gynecologist)
    NormalFunction = ('NormalFunction', Specialist.Gynecologist)
    LacerationAbrassion = ('Laceration_Abrassion', Specialist.Gynecologist)
    VulvarConditionsOther = ('VulvarConditionsOther', Specialist.Gynecologist)
    Dyspareunia = ('Dyspareunia', Specialist.Gynecologist)
    OvaryConditions = ('OvaryConditions', Specialist.Gynecologist)

    PediatricAcuteDiarrhea = ('PediatricAcuteDiarrhea', Specialist.Pediatrician)
    PediatricUpperRespiratoryInfection = ('PediatricUpperRespiratoryInfection', Specialist.Pediatrician)
    PediatricEarInfection = ('PediatricOtitisMedia', Specialist.Pediatrician)
    PediatricAsthma = ('PediatricAsthma', Specialist.Pediatrician)
    PediatricSoreThroat = ('PediatricPharyngitis', Specialist.Pediatrician)
    PediatricBronchiolitis = ('PediatricBronchiolitis', Specialist.Pediatrician)
    PediatricStomachFlu = ('PediatricGastroenteritis', Specialist.Pediatrician)
    PediatricPneumonia = ('PediatricPneumonia', Specialist.Pediatrician)
    PediatricUTI = ('PediatricUrinaryTractInfection', Specialist.Pediatrician)
    PediatricAllergies = ('PediatricAllergies', Specialist.Pediatrician)
    PediatricEczema = ('PediatricEczema', Specialist.Pediatrician)
    PediatricADHD = ('PediatricADHD', Specialist.Pediatrician)
    PediatricCroup = ('PediatricCroup', Specialist.Pediatrician)
    PediatricFebrileSeizures = ('PediatricFebrileSeizures', Specialist.Pediatrician)
    PediatricPinkEye = ('PediatricConjunctivitis', Specialist.Pediatrician)
    PediatricConstipation = ('PediatricConstipation', Specialist.Pediatrician)
    PediatricASD = ('PediatricAutismSpectrumDisorder', Specialist.Pediatrician)
    PediatricKawasakiDisease = ('PediatricKawasakiDisease', Specialist.Pediatrician)
    PediatricHandFootMouthDisease = ('PediatricHandFootMouthDisease', Specialist.Pediatrician)
    PediatricGrowthAndDevelopmentalDelays = ('PediatricGrowthAndDevelopmentalDelays', Specialist.Pediatrician)
    BirthDefect = ('BirthDefect', Specialist.Pediatrician)
    PediatricOther = ('PediatricOther', Specialist.Pediatrician)

    AlcoholUseDisorder = ('AlcoholUseDisorder', Specialist.SubstanceUseDisorderSpecialist)
    AlcoholDependence = ('AlcoholDependence', Specialist.SubstanceUseDisorderSpecialist)
    AlcoholInducedConditions = ('AlcoholInducedConditions', Specialist.SubstanceUseDisorderSpecialist)
    AlcoholRelatedConditions = ('AlcoholRelatedConditions', Specialist.SubstanceUseDisorderSpecialist)
    SubstanceUseOther = ('SubstanceUseOther', Specialist.SubstanceUseDisorderSpecialist)


    SeasonalAllergies = ('SeasonalAllergies', Specialist.Allergist)
    AllergicReactionToMedication = ('AllergicReactionToMedication', Specialist.Allergist)
    AllergicReactionToPlants = ('AllergicReactionToPlants', Specialist.Allergist)
    AllergicReactionToAnimal = ('AllergicReactionToAnimal', Specialist.Allergist)
    AllergicReactionToBite = ('AllergicReactionToBite', Specialist.Allergist)
    AllergicReactionToVaccine = ('AllergicReactionToVaccine', Specialist.Allergist)
    AllergicReactionOtherSubstance = ('AllergicReactionOtherSubstance', Specialist.Allergist)
    AllergicShiners = ('AllergicShiners', Specialist.Allergist)
    AllergicReaction = ('AllergicReaction', Specialist.Allergist)
    AllergiesOther = ('AllergiesOther', Specialist.Allergist)

    AcuteTubularNecrosis = ('AcuteTubularNecrosis', Specialist.RenalSpecialist)
    ChronicKidneyDisease = ('ChronicKidneyDisease', Specialist.RenalSpecialist)
    AcuteKidneyInjury = ('AcuteKidneyInjury', Specialist.RenalSpecialist)
    Glomerulonephritis = ('Glomerulonephritis', Specialist.RenalSpecialist)
    DiabeticNephropathy = ('DiabeticNephropathy', Specialist.RenalSpecialist)
    HypertensiveKidneyDisease = ('HypertensiveKidneyDisease', Specialist.RenalSpecialist)
    PolycysticKidneyDisease = ('PolycysticKidneyDisease', Specialist.RenalSpecialist)
    NephroticSyndrome = ('NephroticSyndrome', Specialist.RenalSpecialist)
    AutoimmuneKidneyDiseases = ('AutoimmuneKidneyDiseases', Specialist.RenalSpecialist)
    Acidosis = ('Acidosis', Specialist.RenalSpecialist)
    InterstitialNephritis = ('InterstitialNephritis', Specialist.RenalSpecialist)
    KidneyDisease = ('Kidney Disease', Specialist.RenalSpecialist)
    RenalSpecialist = ('ElectrolyteDisorders', Specialist.RenalSpecialist)
    RenalDysfunctionNOS = ('RenalDysfunctionNOS', Specialist.RenalSpecialist)
    RenalOther = ('RenalOther', Specialist.RenalSpecialist)
    RenalTubularAcidosis = ('RenalTubularAcidosis', Specialist.RenalSpecialist)

    DentalCaries = ('DentalCaries', Specialist.Dentist)
    PeriodontalDisease = ('PeriodontalDisease', Specialist.Dentist)
    Toothache = ('Toothache', Specialist.Dentist)
    ToothSensitivity = ('ToothSensitivity', Specialist.Dentist)
    ToothAbscess = ('ToothAbscess', Specialist.Dentist)
    Malocclusion = ('Malocclusion', Specialist.Dentist)
    OralInfections = ('OralInfections', Specialist.Dentist)
    TMJDisordersDental = ('TemporomandibularJointDisordersDental', Specialist.Dentist)
    ToothFracturesOrTrauma = ('ToothFracturesOrTrauma', Specialist.Dentist)
    DentalDisordersOther = ('DentalDisordersOther', Specialist.Dentist)

    AdverseReactionToMedication = ('AdverseReactionToMedication', Specialist.AdverseReactionSpecialist)
    AdverseReactionToVaccine = ('AdverseReactionToVaccine', Specialist.AdverseReactionSpecialist)
    AdverseReactionToAnotherSubstance = ('AdverseReactionToAnotherSubstance', Specialist.AdverseReactionSpecialist)
    AdverseReactionSpecialistOther = ('AdverseReactionSpecialistOther', Specialist.AdverseReactionSpecialist)

    Anemia = ('Anemia', Specialist.Hematologist)
    HemophiliaAndBleedingDisorders = ('HemophiliaAndBleedingDisorders', Specialist.Hematologist)
    Thrombocytopenia = ('Thrombocytopenia', Specialist.Hematologist)
    Leukemia = ('Leukemia', Specialist.Hematologist)
    Lymphoma = ('Lymphoma', Specialist.Hematologist)
    MyeloproliferativeDisorders = ('MyeloproliferativeDisorders', Specialist.Hematologist)
    Hemoglobinopathies = ('Hemoglobinopathies', Specialist.Hematologist)
    ThrombosisAndClottingDisorders = ('ThrombosisAndClottingDisorders', Specialist.Hematologist)
    BoneMarrowDisorders = ('BoneMarrowDisorders', Specialist.Hematologist)
    HematologyOther = ('HematologyOther', Specialist.Hematologist)

    RheumatoidArthritis = ('RheumatoidArthritis', Specialist.Rheumatologist)
    OsteoarthritisRheumatology = ('OsteoarthritisRheumatology', Specialist.Rheumatologist)
    SystemicLupusErythematosus = ('SystemicLupusErythematosus', Specialist.Rheumatologist)
    Spondyloarthritis = ('Spondyloarthritis', Specialist.Rheumatologist)
    PsoriaticArthritis = ('PsoriaticArthritis', Specialist.Rheumatologist)
    Gout = ('Gout', Specialist.Rheumatologist)
    SjogrensSyndrome = ('SjogrensSyndrome', Specialist.Rheumatologist)
    SystemicSclerosis = ('SystemicSclerosis', Specialist.Rheumatologist)
    Vasculitis = ('Vasculitis', Specialist.Rheumatologist)
    PolymyalgiaRheumatica = ('PolymyalgiaRheumatica', Specialist.Rheumatologist)
    ImmunodeficiencyCondition = ('ImmunodeficiencyCondition', Specialist.Rheumatologist)
    RheumatologyOther = ('RheumatologyOther', Specialist.Rheumatologist)

    PregnancyConditions = ('PregnancyConditions', Specialist.Obstetrician)

    def __init__(self, inventory_name: str, specialist: Specialist, url_keyword: str = ""):
        self.inventory_name = inventory_name
        self.specialist = specialist
        self.url_keyword = url_keyword
        if url_keyword == "":
            self.url_keyword = inventory_name

    @staticmethod
    def from_url(url: str):
        for subSpec in SubSpecialtyDxGroup:
            if subSpec.url_keyword.lower() == url.lower():
                return subSpec

        logging.warning(f"Url Keyword {url} is not supported. Returning Generalist.")
        return SubSpecialtyDxGroup.Generalist

    @staticmethod
    def from_name(name: str):
        if name is None:
            return SubSpecialtyDxGroup.Generalist
        for spec in SubSpecialtyDxGroup:
            if spec.name.lower() == name.lower():
                return spec

        logging.warning(f"SubSpecialtyDxGroup {name} is not supported. Returning Generalist.")
        return SubSpecialtyDxGroup.Generalist

    @staticmethod
    def from_inventory_name(display_name: str):
        for spec in SubSpecialtyDxGroup:
            if spec.inventory_name.lower() == display_name.lower():
                return spec

        logging.warning(f"Display name {display_name} is not supported for SubSpecialtyDxGroup. Returning Generalist.")
        return SubSpecialtyDxGroup.Generalist

    @staticmethod
    def from_inventory_name_no_default(sub_specialty: str):
        for spec in SubSpecialtyDxGroup:
            if spec.inventory_name.lower() == sub_specialty.lower():
                return spec

        return None

    @staticmethod
    def valid_sub_speciality(specialist: Specialist) -> list:
        return [sub_speciality for sub_speciality in SubSpecialtyDxGroup if sub_speciality.specialist == specialist]
